/**
 * @file main.cpp
 * @brief STM32 example for Sensirion SF04 flow sensor
 *
 * This example demonstrates how to use the SF04 driver on STM32
 *
 * Hardware connections:
 * - I2C1 SDA (PB7)  -> SF04 SDA
 * - I2C1 SCL (PB6)  -> SF04 SCL
 * - 3.3V            -> SF04 VDD
 * - GND             -> SF04 GND
 *
 * Setup:
 * 1. Configure I2C1 peripheral using STM32CubeMX:
 *    - I2C Speed: 100 kHz
 *    - GPIO: PB6 (SCL), PB7 (SDA) with pull-up
 * 2. Configure UART for debug output (e.g., USART2)
 * 3. Enable DWT for accurate microsecond delays (optional)
 *
 * @version 2.0.0
 * @date 2025-11-04
 */

#include "main.h"
#include "sensirion_sf04_v2.h"
#include "hal/stm32/sf04_hal_stm32.h"

// Peripheral handles (initialized by STM32CubeMX)
extern I2C_HandleTypeDef hi2c1;
extern UART_HandleTypeDef huart2;

#define SF04_ADDR 0x40

// Create HAL instances
SF04HAL::stm32::STM32I2C halI2C(&hi2c1);
SF04HAL::stm32::STM32Timing halTiming;
SF04HAL::stm32::STM32Debug halDebug(&huart2);

// Create SF04 sensor instance
SF04 sensor(halI2C, halTiming, SF04_ADDR, 0, 16, &halDebug);

/**
 * @brief System initialization (generated by STM32CubeMX)
 */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);

int main(void)
{
    // Initialize HAL Library
    HAL_Init();

    // Configure system clock
    SystemClock_Config();

    // Initialize peripherals
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();

    // Enable DWT for accurate microsecond delays
    SF04HAL::stm32::enableDWT();

    halDebug.println("\n=== Sensirion SF04 Flow Sensor Example ===");
    halDebug.println("Platform: STM32");
    halDebug.println("Starting up...\n");

    if (sensor.ready) {
        halDebug.printf("Sensor initialized successfully!\n");
        halDebug.printf("Serial Number: %lu\n", sensor.serialNumber.u32);
        halDebug.printf("Scale Factor: %u\n", sensor.scaleFactor.u16);
        halDebug.printf("Flow Unit: %s\n\n", sensor.flowUnitStr);
    } else {
        halDebug.println("ERROR: Sensor initialization failed!");
        halDebug.println("Check connections and I2C address");
        while(1) {
            HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);  // Toggle LED (adjust pin)
            HAL_Delay(100);
        }
    }

    // Main loop
    while (1)
    {
        // Toggle LED to show activity
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);  // Adjust pin for your board

        // Perform measurements
        u8t errorFlow = sensor.Measure(FLOW);
        u8t errorTemp = sensor.Measure(TEMP);
        u8t errorVdd = sensor.Measure(VDD);

        if (errorFlow == 0 && errorTemp == 0 && errorVdd == 0) {
            // Print raw values
            halDebug.printf("Raw - Flow: %d, Temp: %d, Vdd: %u\n",
                          sensor.flow.i16, sensor.temperature.i16, sensor.vdd.u16);

            // Print converted values
            halDebug.printf("Flow: %.2f %s | Temp: %.1f°C | Vdd: %.2fV\n\n",
                          sensor.getFlow(),
                          sensor.flowUnitStr,
                          sensor.getTemperature(),
                          sensor.getVdd());
        } else {
            halDebug.printf("ERROR: Measurement failed (Flow=0x%02X, Temp=0x%02X, Vdd=0x%02X)\n",
                          errorFlow, errorTemp, errorVdd);
        }

        HAL_Delay(1000);  // 1 second delay
    }
}

/**
 * @brief I2C1 Initialization Function (example - adjust for your pins)
 */
static void MX_I2C1_Init(void)
{
    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = 100000;
    hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1 = 0;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2 = 0;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK)
    {
        Error_Handler();
    }
}

/**
 * @brief USART2 Initialization Function (example - adjust for your pins)
 */
static void MX_USART2_UART_Init(void)
{
    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK)
    {
        Error_Handler();
    }
}

/**
 * @brief GPIO Initialization Function
 */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Enable GPIO clocks
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    // Configure LED pin (PA5 for Nucleo boards, adjust for your board)
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

    GPIO_InitStruct.Pin = GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

/**
 * @brief System Clock Configuration (example for STM32F4)
 */
void SystemClock_Config(void)
{
    // Implementation depends on your STM32 series
    // Use STM32CubeMX to generate this function
}

/**
 * @brief Error handler
 */
void Error_Handler(void)
{
    // User can add error handling implementation
    __disable_irq();
    while (1)
    {
    }
}
